server:
  port: 8765

spring:
  application:
    name: service-feign
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost
      port: 6379
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: false

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zzj.servicefeign
logging:
  level:
    com.zzj.servicefeign.dao: DEBUG
